### PR TITLE
Distance metrics

### PR DESCRIPTION
**Pull request by gmrukwa**
I've added mechanism for scalable and normalized distance metric definition, that still may take advantage of some optimizations like those in scipy.

### CODE REVIEW

**Review by Daroslaw — DISMISSED** [review]
Clean and insightful!

**Comment by gmrukwa** [comment]
[Distance measurement mechanism](https://trello.com/c/3tlL9wbE/359-distance-measurement-mechanism)

**Review by Sand3r- — DISMISSED** [review]
Can't think of anything better than license headers really. Well done!

**Comment by gmrukwa** [comment]
Guys, I've found out that tests are not getting discovered correctly (check [this](https://ci.appveyor.com/project/gmrukwa/spectre-divik/build/0.1.0.19/job/5s7ph4j6ev5apgo3#L33)). A little update is incomng.

**Comment by gmrukwa** [comment]
@Sand3r-, good point with that headers.

**Comment by gmrukwa** [comment]
Okay, now it works.

**Comment by gmrukwa** [comment]
I've added license headers too. CodeFactor has some problem with this, but in this case we should just skip its recommendation.

**Review by Daroslaw — APPROVED** [review]

**Review by Sand3r- — APPROVED** [review]

**Pull request merged**
